name: Automation by jira

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 'Person running the test'
        required: true

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Jira API Key and User Input
      run: |
        echo "Using Jira API Key: ${{ secrets.JIRA_API_KEY }}"
        echo "Running test as: ${{ github.event.inputs.user_name }}"
      env:
        JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
