name: Jira Integration

on: [push]

jobs:
  jira-integration-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Publish Test Results to QMetry
      env:
        QM4J_API_KEY: ${{ secrets.JIRA_API_KEY }}
        JIRA_URL: "https://qtmcloud.qmetry.com"
        PROJECT_KEY: "HP"
        CYCLE_ID: "HP-TR-61"
      run: |
        curl -X POST \
          -H apiKey:${JIRA_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{"fields": {"project": {"key": "'"$PROJECT_KEY"'"},"summary": "Automated Test Execution","description": "Results from automated tests","issuetype": {"name": "Test Cycle"},"labels":["automated"],"customfield_10200": "'"$CYCLE_ID"'"}' \
          $JIRA_URL/rest/api/automation/importresult
