name: Jira Integration

on: [push]

jobs:
  jira-integration-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Publish Test Results to QMetry
      env:
        QTM4J_API_KEY: ${{ secrets.QTM4J_AUTOMATION_API_KEY }} 
        JIRA_URL: "https://qtmcloud.qmetry.com/rest/api/automation/importresult"
        PROJECT_KEY: "HP"
        CYCLE_ID: "HP-TR-61"
      run: |
        curl -X POST \
          -H "apiKey:${QTM4J_AUTOMATION_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{"format":"cucumber","testCycleToReuse":"HP-TR-61"}' \
          $JIRA_URL
