name: Jira Integration

on: [push]

jobs:
  jira-integration-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Automated Tests
      run: |
        # Add your command to run tests here, e.g.,
        npm test

    - name: Install QMetry CLI
      run: npm install -g qtm4j-cli

    - name: Publish Test Results to QMetry
       env:
        QTM4J_API_KEY: ${{ secrets.JIRA_API_KEY }}  # Keeping the API key secret for security reasons
      run: |
        PROJECT_KEY="HP"
        CYCLE_ID="HP-TR-61"
        BASE_URL="https://qtmcloud.qmetry.com/rest/api/automation/importresult"

        # Sample test result content
        echo "Test Suite: Sample Test Suite
        ----------------------------
        Test Case 1: Passed
        Test Case 2: Passed
        Test Case 3: Failed
            - Error: Expected value was 42, but got 43
        Test Case 4: Passed
        ----------------------------
        Summary:
        Total Tests: 4
        Passed: 3
        Failed: 1
        Skipped: 0
        ----------------------------
        Execution Time: 2m 35s
        Executed By: Your Name" > test-result.txt

        qtm4j-cli test-import \
        --projectId $PROJECT_KEY \
        --cycleId $CYCLE_ID \
        --apiKey $JIRA_API_KEY \
        --baseUrl $BASE_URL \
        --filePath ./test-result.txt \
        --format text
