name: Jira Integration

on: [push]

jobs:
  jira-integration-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        # Add your test commands here
        echo "Running tests..."
        # Simulate test results (replace with actual test commands)
        echo "Test results generated successfully."

    - name: Create Jira Issue
      env:
        JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}  # Still using secrets for the API token
      run: |
        JIRA_USERNAME="hussishd786@gmail.com"
        JIRA_PROJECT_KEY=HP
        JIRA_SITE="https://hussain-qmetry.atlassian.net"
        
        
        # Example using curl to create a Jira issue (modify as needed to import results)
        curl -u $JIRA_USERNAME:$JIRA_API_KEY -X POST -H "Content-Type: application/json" \
        --data '{
          "fields": {
            "project": {
              "key": "'"$JIRA_PROJECT_KEY"'"
            },
            "summary": "Automated Test Results",
            "description": "Test results imported from GitHub Actions. All tests passed successfully.",
            "issuetype": {
              "name": "Test Cycle"
            }
          }
        }' $JIRA_SITE/rest/api/automation/importresult
