name: Upload Test Result to QMetry

on:
  workflow_dispatch:  # Can be triggered manually or via API (QTM4J webhook)
    inputs:
      testCycleId:
        description: "QMetry Test Cycle ID from webhook or manual input"
        required: false  # optional in case manual trigger

jobs:
  upload-to-qmetry:
    runs-on: ubuntu-latest

    env:
      QTM4J_API_KEY_HUSSAINAGAIN: ${{ secrets.QTM4J_API_KEY_HUSSAINAGAIN }}
      QTM4J_BASE_URL: ${{ secrets.QTM4J_BASE_URL }}     # e.g. https://jira.example.com
      RESULT_FILE: ./JUnit.xml                      # ✅ Path to your local XML file

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 0: Debug - print received test cycle id
      - name: "Debug: Print received test cycle id"
        run: |
          echo "Received test cycle id from webhook: '${{ github.event.inputs.testCycleId }}'"

      # Step 1: Save test cycle id dynamically
      - name: Save test cycle id
        run: |
          KEY="${{ github.event.inputs.testCycleId }}"
          if [ -z "$KEY" ]; then
            echo "No test cycle id provided. Using default placeholder."
            KEY="DEFAULT_TEST_CYCLE"
          fi
          echo "$KEY" > test_cycle_key.txt
          echo "Test cycle id saved: $KEY"

      # Step 2: Debug - check saved file
      - name: Check test_cycle_key.txt
        run: |
          echo "Contents of test_cycle_key.txt:"
          cat test_cycle_key.txt

      # Step 3: Get presigned upload URL from QMetry
      - name: Get presigned URL from QMetry
        id: presign
        run: |
          TEST_CYCLE_KEY=$(cat test_cycle_key.txt)
          cat > payload.json <<EOF
          {
            "format": "JUNIT",
            "isZip": false,
            "testCycleToReuse": "$TEST_CYCLE_KEY",
            "fields": {
              "testCase": {
                "status": "In Progress"
              }
            }
          }
          EOF

          echo "Payload being sent:"
          cat payload.json
          HTTP_STATUS=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "apiKey: $QTM4J_API_KEY_HUSSAINAGAIN" \
            -u "${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_PASSWORD }}" \
            -d @payload.json \
            "$QTM4J_BASE_URL/rest/qtm4j/automation/latest/importresult" \
            -o response.json
          echo "QMetry response:"
          echo "HTTP Status: $HTTP_STATUS"
          cat response.json

          echo "upload_url=$(jq -r '.url' response.json)" >> "$GITHUB_OUTPUT"
          echo "tracking_id=$(jq -r '.trackingId' response.json)" >> "$GITHUB_OUTPUT"

      # Step 4: Upload local XML file using PUT with multipart/form-data
      - name: Upload XML file to QMetry (S3 presigned POST)
        run: |
          echo "Uploading: ${RESULT_FILE}"
          ls -l "${RESULT_FILE}"

          curl --fail -X POST \
             -H "Content-Type: multipart/form-data" \
             -F "file=@${RESULT_FILE}" \
             "${{ steps.presign.outputs.upload_url }}"
