name: Upload Local Test Result to QMetry

on:
  workflow_dispatch:  # Manual trigger

jobs:
  upload-to-qmetry:
    runs-on: ubuntu-latest

    env:
      QTM4J_API_KEY_HUSSAINAGAIN: ${{ secrets.QTM4J_API_KEY_HUSSAINAGAIN }}
      QTM4J_BASE_URL: ${{ secrets.QTM4J_BASE_URL }}     # e.g. https://jira.example.com
      RESULT_FILE: ./JUnit.xml                      # ✅ Path to your local XML file

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 1: Get presigned upload URL from QMetry
      - name: Get presigned URL from QMetry
        id: presign
        run: |
          cat > payload.json <<EOF
          {
            "format": "JUNIT",
            "isZip": false,
            "fields": {
              "testCase": {
                "status": "In Progress"
              }
            }
          }
          EOF

          curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "apiKey: $QTM4J_API_KEY_HUSSAINAGAIN" \
            -d @payload.json \
            "$QTM4J_BASE_URL/rest/api/automation/importresult" \
            -o response.json

          echo "upload_url=$(jq -r '.url' response.json)" >> "$GITHUB_OUTPUT"
          echo "tracking_id=$(jq -r '.trackingId' response.json)" >> "$GITHUB_OUTPUT"

      # Step 2: Upload local XML file using PUT with multipart/form-data
      - name: Upload test result file
        run: |
          curl -X PUT \
               -F "file=@${RESULT_FILE}" \
               "${{ steps.presign.outputs.upload_url }}"
