name: Upload Local Test Result to QMetry

on:
  workflow_dispatch:  # Manual trigger

jobs:
  upload-to-qmetry:
    runs-on: ubuntu-latest

    env:
      QTM4J_API_KEY_HUSSAINAGAIN: ${{ secrets.QTM4J_API_KEY_HUSSAINAGAIN }}
      QTM4J_BASE_URL: ${{ secrets.QTM4J_BASE_URL }}     # e.g. https://jira.example.com
      RESULT_FILE: ./JUnit.xml                      # ✅ Path to your local XML file

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 1: Get presigned upload URL from QMetry
      - name: Get presigned URL from QMetry
        id: presign
        run: |
          cat > payload.json <<EOF
          {
            "format": "JUNIT",
            "isZip": false,
            "fields": {
              "testCase": {
                "status": "In Progress"
              }
            }
          }
          EOF

          curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "apiKey: $QTM4J_API_KEY_HUSSAINAGAIN" \
            -d @payload.json \
            "$QTM4J_BASE_URL/rest/api/automation/importresult" \
            -o response.json

          echo "Presign response:" && cat response.json
          UPLOAD_URL=$(jq -r '.url // empty' response.json)

          if [ -z "$UPLOAD_URL" ]; then
              echo "::error::Presign failed – no upload URL"; exit 1
          fi
          echo "upload_url=$UPLOAD_URL" >> "$GITHUB_OUTPUT"

      - name: Step 2 – Upload XML (PUT multipart)
        run: |
          curl -X PUT \
               -F "file=@${RESULT_FILE}" \
               "${{ steps.presign.outputs.upload_url }}"
