name: Update Jira Issue with Attachment

on:
  push:
    branches:
      - main

jobs:
  update-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Jira Issue with Attachment
      env:
        JIRA_URL: "https://qtm4j-cloud-prod-4.s3.amazonaws.com/automation-uploads/1718931158754_f0c1ad8b-a8e3-44ff-8370-db5027806863.json?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEKn%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJGMEQCIG5PVXG%2BLbUeKqQ%2FNRDY9nyDj8ZQ3UmYpyUffxUfWeWBAiAQzR36AC%2FG7hdahrFQozXXafuYGfFgi7JHmGYThbAazCqxBQhREAQaDDQxNTU1MTIyNTgwNSIM8TkJWGohOQU%2BQnTTKo4FFLx7PO9EJsTwaZetf8QNxjtVBBAJ1cOk3RfwHQ5cUUUWImZYkXmuuS8iMq8feGLviXl4NMEu1KZ%2BmE0JIMu6ZzfjzUABMDROIAXsNcJdjVPFKUQlP9dVKNiParw1esSB8i7zqTf%2BT%2Fhovce5uWavNkzexpuM4ZO9Hh%2BTaGcyBT%2BDYpmEHFlQCQBSHIpT2a9UiRUvm6KWY8bzxnplvslSJmuruY2dZmKKcBFnULuKH0xqVyG1F1hjmfL6vlPS0maBkqPNEmVkOkOX6YHMubVu4SxVbPo601r8LfhwrBaWfRzN0XgtTwBpatuSRyv1hhvJZatYAv7J8A5qnwIn8F%2B2yRWupi5BCU7MZ5G3rX7wvCZYWTV7RyE3qv4Xhb8qxmUaK%2FVxSQQxvZxKVeedkDV4XBcoo1bkGpB8SNAvN2a%2BwPCDaBHs5szz%2F9LmV2DlfsC5FB7awxNzNsZSHoxfVxVB7Nfx%2Fshl09V%2BbIV8PQLhwEIY182cCoMXEFaqWjml2UNUrwOHtX3XE%2FpYIPSrO8nyzizZGrQ3fkfjVowRWWdeGNVnHXlMSFNHqNvcg%2BmgnnhS2Nb23fBW9sxT6mJAAyXrZH8%2FFMbU4WKGr80%2FOiiqqqUcYh7erd1JbKh5obMWLHY2bKJbFVKJspsLYI2EDVmYzg3Oe2mmOsFCk6c4qb38d1w%2B2UFWEuOpu%2FGIcIGblgFQTFLljumxRrYFM8Uz8dF5yFKS7KOw2BPgAsyo9OcWNmenGhOtZzv6EXmu%2BQRNXLZRO4iPqc%2FpdR4ahpk1aD5QphthYOcYhCGDiisgAFuP31FrA%2FnRmcL%2Bc%2BSDz%2FYlEV0zB0ehvLBgl8bVcR6nmdehlxmGShvW5M9iENASyOPwMJ%2BM07MGOrIBngN6LZixSDvM6WM7u2%2BjDVRXUPJVo9nmgbMmcaBDSBKBXNgwgtIa2gnfsFL4zDRucSWru6QYDysUq3vdODMp3MbgwmepWMlDdSOdMBrlU9WBcsh5QkD1AgVFnyF%2BswcFZiXddOMCZrtgiwQQXpAwirZB814GBKGMUyNy%2F3axF4ViVJ9X0IyEKZ%2Flh6DE7CtT8T9qYDfNSmJlf4PZn5omUk0bg8NS5AZe3H%2F5ku4oRY6arw%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240621T005238Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=299&X-Amz-Credential=ASIAWBQGIP7GZ4O4JW56%2F20240621%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=eb388ee95403f1c51ffc1e4ee2e0a52751b4f02e225834c945ce614e9088256f"
      run: |
        # Download the cucumber.json file from the repository
        mkdir temp
        curl -o temp/cucumber.json https://raw.githubusercontent.com/Hussain1952/first_repository/main/cucumber-json-report.json

        # Update the Jira issue with the new summary and description
        curl -X PUT \
          -H "Content-Type:multipart/form-data" \
          -F "file=@temp/cucumber.json" \
          $JIRA_URL
